services:
  db:
    image: postgres:15
    container_name: dayoff-db
    environment:
      POSTGRES_DB: dayoff
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dayoff"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: dayoff-backend
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dayoff
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APPLICATION_SECURITY_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: dayoff-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
